### ISSUE TITLE
 TypeError with 'issued' attribute of type 'NoneType' for operation 'inventory'

### ISSUE THREAD

**Issue by chrlutz** [hzulla/tolino-python#1]
When I do

./tolinoclient.py --user <...> --password <...> --partner 3 inventory

I get the following result:
Traceback (most recent call last):
File "/home/clutz/tolino-python/tolinocloud.py", line 361, in _parse_metadata
'issued' : int(j['epubMetaData']['issued']),
TypeError: int() argument must be a string or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/clutz/tolino-python/tolinocloud.py", line 390, in inventory
inv.append(self._parse_metadata(item))
File "/home/clutz/tolino-python/tolinocloud.py", line 365, in _parse_metadata
raise TolinoException('could not parse metadata')
tolinocloud.TolinoException: could not parse metadata

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./tolinoclient.py", line 153, in
args.func(args)
File "./tolinoclient.py", line 19, in inventory
inv = c.inventory()
File "/home/clutz/tolino-python/tolinocloud.py", line 393, in inventory
raise TolinoException('inventory list request failed.')
tolinocloud.TolinoException: inventory list request failed.

Other operations (I tried "upload" and "devices") seem to work correct for me.

**Comment by hzulla** [comment]
PSA: Hello there. I have stopped maintaining this library, as I do not own a Tolino anymore. If this library is still useful to you, I'd want to hand it over to a new maintainer. Thank you. As this issue is outdated, I'm closing it.
