### ISSUE TITLE
Thalia login oauth code request failed

### ISSUE THREAD

**Issue by clue404** [hzulla/tolino-python#28]
Hi,

sadly there is a problem when I try to connect to the tolino cloud with Thalia.de credentials.

```
Traceback (most recent call last):
  File "/home/clue404/dev/git/tolino-python/tolinocloud.py", line 273, in login
    auth_code = params['code'][0]
KeyError: 'code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tolinoclient.py", line 161, in <module>
    args.func(args)
  File "tolinoclient.py", line 19, in inventory
    c.login(args.user, args.password)
  File "/home/clue404/dev/git/tolino-python/tolinocloud.py", line 275, in login
    raise TolinoException('oauth code request failed.')
tolinocloud.TolinoException: oauth code request failed.
```

I am using master Branch.

Thanks in advance for any help

**Comment by clue404** [comment]
Okay I found the error. 
I added my username and password into tolinoclientrc in quotes like "username". But you have to enter them like username.
