### ISSUE TITLE
devices results in KeyError: 20

### ISSUE THREAD

**Issue by michote** [hzulla/tolino-python#3]
```
$ python3 tolinoclient.py devices
4 devices connected to tolino cloud account *****

device    : *******
type      : tolino_vision_2
name      : None
Traceback (most recent call last):
  File "tolinoclient.py", line 153, in <module>
    args.func(args)
  File "tolinoclient.py", line 54, in devices
    print('partner   : {} / {}'.format(d['partner'], TolinoCloud.partner_mapping[d['partner']]))
KeyError: 20 
```

**Comment by hzulla** [comment]
Thanks. Will fix that.

**Comment by hzulla** [comment]
Should be fixed with https://github.com/hzulla/tolino-python/commit/70a96880aa302e92507d89f8cbe60e78b0d69683

Please give it a try.

**Comment by michote** [comment]
works fine now, thanks.

**Comment by hzulla** [comment]
thanks!
