### ISSUE TITLE
tolinocloud.TolinoException: oauth access token request failed.

### ISSUE THREAD

**Issue by Gomez** [hzulla/tolino-python#4]
Thanks for this script. Does it is still in use? I get this error:
```
Traceback (most recent call last):
  File "/jail/scripts/tolino-python/tolinocloud.py", line 235, in login
    self.access_token = base64.b64decode(b64).decode('utf-8')
  File "/usr/lib/python3.1/base64.py", line 80, in b64decode
    raise TypeError("expected bytes, not %s" % s.__class__.__name__)
TypeError: expected bytes, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tolinoclient.py", line 158, in <module>
    args.func(args)
  File "tolinoclient.py", line 68, in upload
    c.login(args.user, args.password)
  File "/jail/scripts/tolino-python/tolinocloud.py", line 237, in login
    raise TolinoException('oauth access token request failed.')
tolinocloud.TolinoException: oauth access token request failed.
```

I used thalia.de (3).

**Comment by Gomez** [comment]
Does not work with Python below 3.4. 

Maybe it should go into the Readme?

**Comment by hzulla** [comment]
Sorry for the delay.

Please try again, it should work with the most recent commit https://github.com/hzulla/tolino-python/commit/26c4cef7b3da5a78f4b8d6a74b17322b79a91dc9

**Comment by Gomez** [comment]
Thanks. Seems to work again!

**Comment by rtens** [comment]
Thanks for the fix =)
